name: Release on Thunderstore, NuGet

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # clone repo
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # install gitversion
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      # determine version
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7

      # setup nuget.exe
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      # build project
      - run: dotnet build . --configuration Release --output ./ReleaseOutput -p:Version=$GitVersion_MajorMinorPatch

      # retain only wetstone files
      - name: Cleanup Release Output
        run: |
          find ./ReleaseOutput ! -name Wetstone.dll ! -name Wetstone.xml ! -name Wetstone*.nupkg -type f -delete

      # publish to nuget
      - name: Publish to NuGet
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json'

      # install tcli
      - name: Install TCLI
        run: dotnet tool install --global tcli

      # filter out files we don't want in our release
      - name: Cleanup Release Output for TS Release
        run: rm ReleaseOutput/*.nupkg

      # publish
      - name: Publish to thunderstore.io
        run: tcli publish --token ${{ secrets.THUNDERSTORE_DEV_API_KEY }} --package-version ${{ env.GitVersion_MajorMinorPatch }} --config-path ./thunderstore.toml
